language: php
php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install: sh travis.sh
script:
  - cd _test
  - phpunit --group plugin_bureaucracy
